// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_bouton', function() {
  
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    await driver.sleep(30)
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
    
  })
  it('test_bouton', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1200, height: 771 })
    await driver.findElement(By.name("Name")).click()
    await driver.findElement(By.name("Name")).sendKeys("test")
    await driver.findElement(By.name("nom")).click()
    assert(await driver.switchTo().alert().getText() == "Success")
  })
})
